# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/space_things/create_space_things.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_things_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__things__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__things__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__things__domain__pb2.google.protobuf.timestamp_pb2
from ethos.elint.collars import DC499999997_pb2 as ethos_dot_elint_dot_collars_dot_DC499999997__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC499999997__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC499999997__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLethos/elint/services/product/identity/space_things/create_space_things.proto\x12%elint.services.product.identity.space\x1a.ethos/elint/entities/space_things_domain.proto\x1a%ethos/elint/collars/DC499999997.proto\"\xe1\x01\n\x1e\x43reateThingsSpaceDomainRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12i\n\nproperties\x18\x03 \x03(\x0b\x32U.elint.services.product.identity.space.CreateThingsSpaceDomainRequest.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"R\n\x1f\x43reateThingsSpaceDomainResponse\x12/\n\x06\x64omain\x18\x01 \x01(\x0b\x32\x1f.elint.entity.SpaceThingsDomain\"F\n\x18\x43reateNodesCollarRequest\x12*\n\x06\x63ollar\x18\x01 \x01(\x0b\x32\x1a.elint.collars.DC499999997\"G\n\x19\x43reateNodesCollarResponse\x12*\n\x06\x63ollar\x18\x01 \x01(\x0b\x32\x1a.elint.collars.DC4999999972\xd3\x02\n\rCreateService\x12\xa8\x01\n\x17\x43reateThingsSpaceDomain\x12\x45.elint.services.product.identity.space.CreateThingsSpaceDomainRequest\x1a\x46.elint.services.product.identity.space.CreateThingsSpaceDomainResponse\x12\x96\x01\n\x11\x43reateNodesCollar\x12?.elint.services.product.identity.space.CreateNodesCollarRequest\x1a@.elint.services.product.identity.space.CreateNodesCollarResponseB6\n%elint.services.product.identity.spaceB\x0b\x43reateProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.space_things.create_space_things_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%elint.services.product.identity.spaceB\013CreateProtoP\001'
  _globals['_CREATETHINGSSPACEDOMAINREQUEST_PROPERTIESENTRY']._options = None
  _globals['_CREATETHINGSSPACEDOMAINREQUEST_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_CREATETHINGSSPACEDOMAINREQUEST']._serialized_start=207
  _globals['_CREATETHINGSSPACEDOMAINREQUEST']._serialized_end=432
  _globals['_CREATETHINGSSPACEDOMAINREQUEST_PROPERTIESENTRY']._serialized_start=383
  _globals['_CREATETHINGSSPACEDOMAINREQUEST_PROPERTIESENTRY']._serialized_end=432
  _globals['_CREATETHINGSSPACEDOMAINRESPONSE']._serialized_start=434
  _globals['_CREATETHINGSSPACEDOMAINRESPONSE']._serialized_end=516
  _globals['_CREATENODESCOLLARREQUEST']._serialized_start=518
  _globals['_CREATENODESCOLLARREQUEST']._serialized_end=588
  _globals['_CREATENODESCOLLARRESPONSE']._serialized_start=590
  _globals['_CREATENODESCOLLARRESPONSE']._serialized_end=661
  _globals['_CREATESERVICE']._serialized_start=664
  _globals['_CREATESERVICE']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
