# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.space_things import delete_space_things_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2


class DeleteServiceStub(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteThingsSpaceDomain = channel.unary_unary(
                '/elint.services.product.identity.space.DeleteService/DeleteThingsSpaceDomain',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteThingsSpaceDomainRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteThingsSpaceDomainResponse.FromString,
                )
        self.DeleteNodesCollar = channel.unary_unary(
                '/elint.services.product.identity.space.DeleteService/DeleteNodesCollar',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteNodesCollarRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteNodesCollarResponse.FromString,
                )


class DeleteServiceServicer(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def DeleteThingsSpaceDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNodesCollar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteThingsSpaceDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteThingsSpaceDomain,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteThingsSpaceDomainRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteThingsSpaceDomainResponse.SerializeToString,
            ),
            'DeleteNodesCollar': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNodesCollar,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteNodesCollarRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteNodesCollarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.space.DeleteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeleteService(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    @staticmethod
    def DeleteThingsSpaceDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.space.DeleteService/DeleteThingsSpaceDomain',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteThingsSpaceDomainRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteThingsSpaceDomainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNodesCollar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.space.DeleteService/DeleteNodesCollar',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteNodesCollarRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_delete__space__things__pb2.DeleteNodesCollarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
