# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/space_things/delete_space_things.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_things_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__things__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__things__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__things__domain__pb2.google.protobuf.timestamp_pb2
from ethos.elint.collars import DC499999997_pb2 as ethos_dot_elint_dot_collars_dot_DC499999997__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC499999997__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC499999997__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLethos/elint/services/product/identity/space_things/delete_space_things.proto\x12%elint.services.product.identity.space\x1a.ethos/elint/entities/space_things_domain.proto\x1a%ethos/elint/collars/DC499999997.proto\".\n\x1e\x44\x65leteThingsSpaceDomainRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x1f\x44\x65leteThingsSpaceDomainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"1\n\x18\x44\x65leteNodesCollarRequest\x12\x15\n\rmachine_class\x18\x01 \x01(\t\",\n\x19\x44\x65leteNodesCollarResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd3\x02\n\rDeleteService\x12\xa8\x01\n\x17\x44\x65leteThingsSpaceDomain\x12\x45.elint.services.product.identity.space.DeleteThingsSpaceDomainRequest\x1a\x46.elint.services.product.identity.space.DeleteThingsSpaceDomainResponse\x12\x96\x01\n\x11\x44\x65leteNodesCollar\x12?.elint.services.product.identity.space.DeleteNodesCollarRequest\x1a@.elint.services.product.identity.space.DeleteNodesCollarResponseB6\n%elint.services.product.identity.spaceB\x0b\x44\x65leteProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.space_things.delete_space_things_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%elint.services.product.identity.spaceB\013DeleteProtoP\001'
  _globals['_DELETETHINGSSPACEDOMAINREQUEST']._serialized_start=206
  _globals['_DELETETHINGSSPACEDOMAINREQUEST']._serialized_end=252
  _globals['_DELETETHINGSSPACEDOMAINRESPONSE']._serialized_start=254
  _globals['_DELETETHINGSSPACEDOMAINRESPONSE']._serialized_end=304
  _globals['_DELETENODESCOLLARREQUEST']._serialized_start=306
  _globals['_DELETENODESCOLLARREQUEST']._serialized_end=355
  _globals['_DELETENODESCOLLARRESPONSE']._serialized_start=357
  _globals['_DELETENODESCOLLARRESPONSE']._serialized_end=401
  _globals['_DELETESERVICE']._serialized_start=404
  _globals['_DELETESERVICE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
