# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/space_things/read_space_things.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_things_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__things__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__things__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__things__domain__pb2.google.protobuf.timestamp_pb2
from ethos.elint.collars import DC499999997_pb2 as ethos_dot_elint_dot_collars_dot_DC499999997__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC499999997__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC499999997__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJethos/elint/services/product/identity/space_things/read_space_things.proto\x12%elint.services.product.identity.space\x1a.ethos/elint/entities/space_things_domain.proto\x1a%ethos/elint/collars/DC499999997.proto\",\n\x1cReadThingsSpaceDomainRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"P\n\x1dReadThingsSpaceDomainResponse\x12/\n\x06\x64omain\x18\x01 \x01(\x0b\x32\x1f.elint.entity.SpaceThingsDomain\"+\n\x16ReadNodesCollarRequest\x12\x11\n\tcollar_id\x18\x01 \x01(\t\"E\n\x17ReadNodesCollarResponse\x12*\n\x06\x63ollar\x18\x01 \x01(\x0b\x32\x1a.elint.collars.DC4999999972\xc5\x02\n\x0bReadService\x12\xa2\x01\n\x15ReadThingsSpaceDomain\x12\x43.elint.services.product.identity.space.ReadThingsSpaceDomainRequest\x1a\x44.elint.services.product.identity.space.ReadThingsSpaceDomainResponse\x12\x90\x01\n\x0fReadNodesCollar\x12=.elint.services.product.identity.space.ReadNodesCollarRequest\x1a>.elint.services.product.identity.space.ReadNodesCollarResponseB4\n%elint.services.product.identity.spaceB\tReadProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.space_things.read_space_things_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%elint.services.product.identity.spaceB\tReadProtoP\001'
  _globals['_READTHINGSSPACEDOMAINREQUEST']._serialized_start=204
  _globals['_READTHINGSSPACEDOMAINREQUEST']._serialized_end=248
  _globals['_READTHINGSSPACEDOMAINRESPONSE']._serialized_start=250
  _globals['_READTHINGSSPACEDOMAINRESPONSE']._serialized_end=330
  _globals['_READNODESCOLLARREQUEST']._serialized_start=332
  _globals['_READNODESCOLLARREQUEST']._serialized_end=375
  _globals['_READNODESCOLLARRESPONSE']._serialized_start=377
  _globals['_READNODESCOLLARRESPONSE']._serialized_end=446
  _globals['_READSERVICE']._serialized_start=449
  _globals['_READSERVICE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
