# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.space_things import read_space_things_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2


class ReadServiceStub(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadThingsSpaceDomain = channel.unary_unary(
                '/elint.services.product.identity.space.ReadService/ReadThingsSpaceDomain',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadThingsSpaceDomainRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadThingsSpaceDomainResponse.FromString,
                )
        self.ReadNodesCollar = channel.unary_unary(
                '/elint.services.product.identity.space.ReadService/ReadNodesCollar',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadNodesCollarRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadNodesCollarResponse.FromString,
                )


class ReadServiceServicer(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def ReadThingsSpaceDomain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadNodesCollar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadThingsSpaceDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadThingsSpaceDomain,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadThingsSpaceDomainRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadThingsSpaceDomainResponse.SerializeToString,
            ),
            'ReadNodesCollar': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadNodesCollar,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadNodesCollarRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadNodesCollarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.space.ReadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReadService(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    @staticmethod
    def ReadThingsSpaceDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.space.ReadService/ReadThingsSpaceDomain',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadThingsSpaceDomainRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadThingsSpaceDomainResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadNodesCollar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.space.ReadService/ReadNodesCollar',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadNodesCollarRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space__things_dot_read__space__things__pb2.ReadNodesCollarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
