# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge_domain_file/delete_space_knowledge_domain_file.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_knowledge_domain_file_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__pb2
from ethos.elint.services.product.knowledge.space_knowledge_domain import access_space_knowledge_domain_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain_dot_access__space__knowledge__domain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nkethos/elint/services/product/knowledge/space_knowledge_domain_file/delete_space_knowledge_domain_file.proto\x12%elint.services.product.knowledge.file\x1a\"ethos/elint/entities/generic.proto\x1a\x36\x65thos/elint/entities/space_knowledge_domain_file.proto\x1a\x61\x65thos/elint/services/product/knowledge/space_knowledge_domain/access_space_knowledge_domain.proto\"\x8a\x02\n%DeleteSpaceKnowledgeDomainFileRequest\x12\x93\x01\n3space_knowledge_domain_services_access_auth_details\x18\x01 \x01(\x0b\x32V.elint.services.product.knowledge.domain.SpaceKnowledgeDomainServicesAccessAuthDetails\x12K\n\x1bspace_knowledge_domain_file\x18\x02 \x01(\x0b\x32&.elint.entity.SpaceKnowledgeDomainFile2\xb6\x01\n%DeleteSpaceKnowledgeDomainFileService\x12\x8c\x01\n\x1e\x44\x65leteSpaceKnowledgeDomainFile\x12L.elint.services.product.knowledge.file.DeleteSpaceKnowledgeDomainFileRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.knowledge.space_knowledge_domain_file.delete_space_knowledge_domain_file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DELETESPACEKNOWLEDGEDOMAINFILEREQUEST']._serialized_start=342
  _globals['_DELETESPACEKNOWLEDGEDOMAINFILEREQUEST']._serialized_end=608
  _globals['_DELETESPACEKNOWLEDGEDOMAINFILESERVICE']._serialized_start=611
  _globals['_DELETESPACEKNOWLEDGEDOMAINFILESERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
