# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.entities import space_knowledge_domain_file_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__pb2
from ethos.elint.services.product.knowledge.space_knowledge_domain_file import discover_space_knowledge_domain_file_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2


class DiscoverKnowledgeDomainFileServiceStub(object):
    """Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFileByID = channel.unary_unary(
                '/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/GetFileByID',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.GetFileByIDRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__pb2.SpaceKnowledgeDomainFile.FromString,
                )
        self.FileExistsByID = channel.unary_unary(
                '/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/FileExistsByID',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.FileExistsByIDRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.FileExistsByIDResponse.FromString,
                )
        self.Download = channel.unary_stream(
                '/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/Download',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.DownloadRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.DownloadResponse.FromString,
                )


class DiscoverKnowledgeDomainFileServiceServicer(object):
    """Service Definition
    """

    def GetFileByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FileExistsByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoverKnowledgeDomainFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFileByID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileByID,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.GetFileByIDRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__pb2.SpaceKnowledgeDomainFile.SerializeToString,
            ),
            'FileExistsByID': grpc.unary_unary_rpc_method_handler(
                    servicer.FileExistsByID,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.FileExistsByIDRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.FileExistsByIDResponse.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.DownloadRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.DownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoverKnowledgeDomainFileService(object):
    """Service Definition
    """

    @staticmethod
    def GetFileByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/GetFileByID',
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.GetFileByIDRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__pb2.SpaceKnowledgeDomainFile.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FileExistsByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/FileExistsByID',
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.FileExistsByIDRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.FileExistsByIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/elint.services.product.knowledge.file.DiscoverKnowledgeDomainFileService/Download',
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.DownloadRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_discover__space__knowledge__domain__file__pb2.DownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
