# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.product.space_product_domain import access_space_product_domain_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2


class AccessSpaceProductDomainServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpaceProductDomainAccessToken = channel.unary_unary(
                '/elint.services.product.product.domain.AccessSpaceProductDomainService/SpaceProductDomainAccessToken',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainAccessTokenRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainAccessTokenResponse.FromString,
                )
        self.ValidateSpaceProductDomainServices = channel.unary_unary(
                '/elint.services.product.product.domain.AccessSpaceProductDomainService/ValidateSpaceProductDomainServices',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.ValidateSpaceProductDomainServicesResponse.FromString,
                )


class AccessSpaceProductDomainServiceServicer(object):
    """Service Definitions
    """

    def SpaceProductDomainAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSpaceProductDomainServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessSpaceProductDomainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpaceProductDomainAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.SpaceProductDomainAccessToken,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainAccessTokenRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainAccessTokenResponse.SerializeToString,
            ),
            'ValidateSpaceProductDomainServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSpaceProductDomainServices,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.ValidateSpaceProductDomainServicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.product.domain.AccessSpaceProductDomainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessSpaceProductDomainService(object):
    """Service Definitions
    """

    @staticmethod
    def SpaceProductDomainAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.product.domain.AccessSpaceProductDomainService/SpaceProductDomainAccessToken',
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainAccessTokenRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateSpaceProductDomainServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.product.domain.AccessSpaceProductDomainService/ValidateSpaceProductDomainServices',
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.SpaceProductDomainServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2.ValidateSpaceProductDomainServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
