# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
from ethos.elint.services.product.product.space_product_domain import create_space_product_domain_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_create__space__product__domain__pb2


class CreateSpaceProductDomainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDC499999994 = channel.unary_unary(
                '/elint.services.product.product.domain.CreateSpaceProductDomainService/CreateDC499999994',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_create__space__product__domain__pb2.CreateDC499999994SPDRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )


class CreateSpaceProductDomainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDC499999994(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateSpaceProductDomainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDC499999994': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDC499999994,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_create__space__product__domain__pb2.CreateDC499999994SPDRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.product.domain.CreateSpaceProductDomainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreateSpaceProductDomainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDC499999994(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.product.domain.CreateSpaceProductDomainService/CreateDC499999994',
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_create__space__product__domain__pb2.CreateDC499999994SPDRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
