# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/product/space_product_domain/create_space_product_domain.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_product_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__product__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__product__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__product__domain__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.product.space_product import access_space_product_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2
from ethos.elint.services.product.product.space_product_domain import access_space_product_domain_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2
from ethos.elint.collars import DC499999994_pb2 as ethos_dot_elint_dot_collars_dot_DC499999994__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[ethos/elint/services/product/product/space_product_domain/create_space_product_domain.proto\x12%elint.services.product.product.domain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"ethos/elint/entities/generic.proto\x1a/ethos/elint/entities/space_product_domain.proto\x1aMethos/elint/services/product/product/space_product/access_space_product.proto\x1a[ethos/elint/services/product/product/space_product_domain/access_space_product_domain.proto\x1a%ethos/elint/collars/DC499999994.proto\"\xe1\x01\n\x1b\x43reateDC499999994SPDRequest\x12Y\n\x04\x61uth\x18\x01 \x01(\x0b\x32K.elint.services.product.product.space.SpaceProductServicesAccessAuthDetails\x12\x0c\n\x04name\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x0c \x01(\t\x12\x13\n\x0bis_isolated\x18\r \x01(\x08\x12/\n\x0b\x64\x63\x34\x39\x39\x39\x39\x39\x39\x39\x34\x18\x0e \x01(\x0b\x32\x1a.elint.collars.DC4999999942\x98\x01\n\x1f\x43reateSpaceProductDomainService\x12u\n\x11\x43reateDC499999994\x12\x42.elint.services.product.product.domain.CreateDC499999994SPDRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.product.space_product_domain.create_space_product_domain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEDC499999994SPDREQUEST']._serialized_start=464
  _globals['_CREATEDC499999994SPDREQUEST']._serialized_end=689
  _globals['_CREATESPACEPRODUCTDOMAINSERVICE']._serialized_start=692
  _globals['_CREATESPACEPRODUCTDOMAINSERVICE']._serialized_end=844
# @@protoc_insertion_point(module_scope)
