apiVersion: v1
kind: Service
metadata:
  name: python-package-index-svc
  namespace: multiverse-delivery
spec:
  type: ClusterIP
  selector:
    epod: eapp-python-package-index
  ports:
    - name: index-http
      protocol: TCP
      port: 80
      targetPort: 8080