# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge/access_space_knowledge.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_knowledge_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.space import access_space_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nSethos/elint/services/product/knowledge/space_knowledge/access_space_knowledge.proto\x12&elint.services.product.knowledge.space\x1a\"ethos/elint/entities/generic.proto\x1a\"ethos/elint/entities/account.proto\x1a*ethos/elint/entities/space_knowledge.proto\x1a>ethos/elint/services/product/identity/space/access_space.proto\"\x8a\x02\n!SpaceKnowledgeAccessTokenResponse\x12\x85\x01\n,space_knowledge_services_access_auth_details\x18\x01 \x01(\x0b\x32O.elint.services.product.knowledge.space.SpaceKnowledgeServicesAccessAuthDetails\x12,\n$space_knowledge_services_access_done\x18\x02 \x01(\x08\x12/\n\'space_knowledge_services_access_message\x18\x03 \x01(\t\"\x9d\x01\n&ValidateSpaceKnowledgeServicesResponse\x12\x37\n/space_knowledge_services_access_validation_done\x18\x01 \x01(\x08\x12:\n2space_knowledge_services_access_validation_message\x18\x02 \x01(\t\"\xfe\x01\n\'SpaceKnowledgeServicesAccessAuthDetails\x12\x35\n\x0fspace_knowledge\x18\x01 \x01(\x0b\x32\x1c.elint.entity.SpaceKnowledge\x12j\n5space_knowledge_services_access_session_token_details\x18\x02 \x01(\x0b\x32+.elint.entity.PersistentSessionTokenDetails\x12\x30\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x95\x03\n\x1b\x41\x63\x63\x65ssSpaceKnowledgeService\x12\xaf\x01\n\x19SpaceKnowledgeAccessToken\x12\x45.elint.services.product.identity.space.SpaceServicesAccessAuthDetails\x1aI.elint.services.product.knowledge.space.SpaceKnowledgeAccessTokenResponse\"\x00\x12\xc3\x01\n\x1eValidateSpaceKnowledgeServices\x12O.elint.services.product.knowledge.space.SpaceKnowledgeServicesAccessAuthDetails\x1aN.elint.services.product.knowledge.space.ValidateSpaceKnowledgeServicesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.knowledge.space_knowledge.access_space_knowledge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPACEKNOWLEDGEACCESSTOKENRESPONSE']._serialized_start=308
  _globals['_SPACEKNOWLEDGEACCESSTOKENRESPONSE']._serialized_end=574
  _globals['_VALIDATESPACEKNOWLEDGESERVICESRESPONSE']._serialized_start=577
  _globals['_VALIDATESPACEKNOWLEDGESERVICESRESPONSE']._serialized_end=734
  _globals['_SPACEKNOWLEDGESERVICESACCESSAUTHDETAILS']._serialized_start=737
  _globals['_SPACEKNOWLEDGESERVICESACCESSAUTHDETAILS']._serialized_end=991
  _globals['_ACCESSSPACEKNOWLEDGESERVICE']._serialized_start=994
  _globals['_ACCESSSPACEKNOWLEDGESERVICE']._serialized_end=1399
# @@protoc_insertion_point(module_scope)
