# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/account_assistant/create_account_assistant.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_assistant_pb2 as ethos_dot_elint_dot_entities_dot_account__assistant__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__assistant__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__assistant__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.account import access_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2
from ethos.elint.services.product.identity.account_assistant import access_account_assistant_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account__assistant_dot_access__account__assistant__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVethos/elint/services/product/identity/account_assistant/create_account_assistant.proto\x12\x31\x65lint.services.product.identity.account.assistant\x1a,ethos/elint/entities/account_assistant.proto\x1a\"ethos/elint/entities/generic.proto\x1a\x42\x65thos/elint/services/product/identity/account/access_account.proto\x1aVethos/elint/services/product/identity/account_assistant/access_account_assistant.proto\"\xa7\x01\n\x1d\x43reateAccountAssistantRequest\x12\x66\n\x13\x61\x63\x63\x65ss_auth_details\x18\x01 \x01(\x0b\x32I.elint.services.product.identity.account.AccountServicesAccessAuthDetails\x12\x1e\n\x16\x61\x63\x63ount_assistant_name\x18\x02 \x01(\t\"\xea\x01\n\x1e\x43reateAccountAssistantResponse\x12\x94\x01\n.account_assistant_services_access_auth_details\x18\x01 \x01(\x0b\x32\\.elint.services.product.identity.account.assistant.AccountAssistantServicesAccessAuthDetails\x12\x31\n\rresponse_meta\x18\x02 \x01(\x0b\x32\x1a.elint.entity.ResponseMeta\"\xac\x01\n\"GetAccountAssistantNameCodeRequest\x12\x66\n\x13\x61\x63\x63\x65ss_auth_details\x18\x01 \x01(\x0b\x32I.elint.services.product.identity.account.AccountServicesAccessAuthDetails\x12\x1e\n\x16\x61\x63\x63ount_assistant_name\x18\x02 \x01(\t\"}\n#GetAccountAssistantNameCodeResponse\x12#\n\x1b\x61\x63\x63ount_assistant_name_code\x18\x01 \x01(\x05\x12\x31\n\rresponse_meta\x18\x02 \x01(\x0b\x32\x1a.elint.entity.ResponseMeta2\xb2\x03\n\x1d\x43reateAccountAssistantService\x12\xbf\x01\n\x16\x43reateAccountAssistant\x12P.elint.services.product.identity.account.assistant.CreateAccountAssistantRequest\x1aQ.elint.services.product.identity.account.assistant.CreateAccountAssistantResponse\"\x00\x12\xce\x01\n\x1bGetAccountAssistantNameCode\x12U.elint.services.product.identity.account.assistant.GetAccountAssistantNameCodeRequest\x1aV.elint.services.product.identity.account.assistant.GetAccountAssistantNameCodeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.account_assistant.create_account_assistant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEACCOUNTASSISTANTREQUEST']._serialized_start=380
  _globals['_CREATEACCOUNTASSISTANTREQUEST']._serialized_end=547
  _globals['_CREATEACCOUNTASSISTANTRESPONSE']._serialized_start=550
  _globals['_CREATEACCOUNTASSISTANTRESPONSE']._serialized_end=784
  _globals['_GETACCOUNTASSISTANTNAMECODEREQUEST']._serialized_start=787
  _globals['_GETACCOUNTASSISTANTNAMECODEREQUEST']._serialized_end=959
  _globals['_GETACCOUNTASSISTANTNAMECODERESPONSE']._serialized_start=961
  _globals['_GETACCOUNTASSISTANTNAMECODERESPONSE']._serialized_end=1086
  _globals['_CREATEACCOUNTASSISTANTSERVICE']._serialized_start=1089
  _globals['_CREATEACCOUNTASSISTANTSERVICE']._serialized_end=1523
# @@protoc_insertion_point(module_scope)
