# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/universe/create_universe.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import universe_pb2 as ethos_dot_elint_dot_entities_dot_universe__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_universe__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_universe__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDethos/elint/services/product/identity/universe/create_universe.proto\x12(elint.services.product.identity.universe\x1a#ethos/elint/entities/universe.proto\x1a\"ethos/elint/entities/generic.proto\"L\n\x15\x43reateUniverseRequest\x12\x15\n\runiverse_name\x18\x01 \x01(\t\x12\x1c\n\x14universe_description\x18\x02 \x01(\t\"\xbf\x01\n\x16\x43reateUniverseResponse\x12\x15\n\runiverse_name\x18\x01 \x01(\t\x12\x37\n\x13universe_created_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1c\n\x14universe_description\x18\x03 \x01(\t\x12\x37\n\x13universe_updated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xad\x01\n\x15\x43reateUniverseService\x12\x93\x01\n\x0e\x43reateUniverse\x12?.elint.services.product.identity.universe.CreateUniverseRequest\x1a@.elint.services.product.identity.universe.CreateUniverseResponseBA\n(elint.services.product.identity.universeB\x13\x43reateUniverseProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.universe.create_universe_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(elint.services.product.identity.universeB\023CreateUniverseProtoP\001'
  _globals['_CREATEUNIVERSEREQUEST']._serialized_start=187
  _globals['_CREATEUNIVERSEREQUEST']._serialized_end=263
  _globals['_CREATEUNIVERSERESPONSE']._serialized_start=266
  _globals['_CREATEUNIVERSERESPONSE']._serialized_end=457
  _globals['_CREATEUNIVERSESERVICE']._serialized_start=460
  _globals['_CREATEUNIVERSESERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
