# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.universe import delete_universe_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2


class DeleteUniverseServiceStub(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteUniverse = channel.unary_unary(
                '/elint.services.product.identity.universe.DeleteUniverseService/DeleteUniverse',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2.DeleteUniverseRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2.DeleteUniverseResponse.FromString,
                )


class DeleteUniverseServiceServicer(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def DeleteUniverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteUniverseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUniverse,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2.DeleteUniverseRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2.DeleteUniverseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.universe.DeleteUniverseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeleteUniverseService(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    @staticmethod
    def DeleteUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.universe.DeleteUniverseService/DeleteUniverse',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2.DeleteUniverseRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_delete__universe__pb2.DeleteUniverseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
