# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.entities import universe_pb2 as ethos_dot_elint_dot_entities_dot_universe__pb2


class DiscoverUniverseServiceStub(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ByID = channel.unary_unary(
                '/elint.services.product.identity.universe.DiscoverUniverseService/ByID',
                request_serializer=ethos_dot_elint_dot_entities_dot_universe__pb2.Universe.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_universe__pb2.Universe.FromString,
                )


class DiscoverUniverseServiceServicer(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def ByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoverUniverseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ByID': grpc.unary_unary_rpc_method_handler(
                    servicer.ByID,
                    request_deserializer=ethos_dot_elint_dot_entities_dot_universe__pb2.Universe.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_universe__pb2.Universe.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.universe.DiscoverUniverseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoverUniverseService(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    @staticmethod
    def ByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.universe.DiscoverUniverseService/ByID',
            ethos_dot_elint_dot_entities_dot_universe__pb2.Universe.SerializeToString,
            ethos_dot_elint_dot_entities_dot_universe__pb2.Universe.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
