# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.universe import update_universe_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2


class UpdateUniverseServiceStub(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateUniverse = channel.unary_unary(
                '/elint.services.product.identity.universe.UpdateUniverseService/UpdateUniverse',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2.UpdateUniverseRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2.UpdateUniverseResponse.FromString,
                )


class UpdateUniverseServiceServicer(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    def UpdateUniverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateUniverseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUniverse,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2.UpdateUniverseRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2.UpdateUniverseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.universe.UpdateUniverseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpdateUniverseService(object):
    """------------------------------------
    Service Definitions
    ------------------------------------
    """

    @staticmethod
    def UpdateUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.universe.UpdateUniverseService/UpdateUniverse',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2.UpdateUniverseRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_update__universe__pb2.UpdateUniverseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
