# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gramx/seventy/zero/ethos/gramxpro/multiverse/core/entity/epe_1001/contract.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPgramx/seventy/zero/ethos/gramxpro/multiverse/core/entity/epe_1001/contract.proto\x12\x41gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1001\"w\n\x07\x45PE1001\x12[\n\x04\x63ode\x18\x01 \x01(\x0e\x32M.gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1001.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\x1b\n\nStatusCode\x12\r\n\tCANCELLED\x10\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1001.contract_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUSCODE._serialized_start=272
  _STATUSCODE._serialized_end=299
  _EPE1001._serialized_start=151
  _EPE1001._serialized_end=270
# @@protoc_insertion_point(module_scope)
