# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/collars/DC499999996.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ethos/elint/collars/DC499999996.proto\x12\relint.collars\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\x0b\x44\x43\x34\x39\x39\x39\x39\x39\x39\x39\x36\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x39\n\x10jupyter_notebook\x18\x88\' \x01(\x0b\x32\x1e.elint.collars.JupyterNotebook\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1d\n\x0fJupyterNotebook\x12\n\n\x02id\x18\x01 \x01(\t\"\x17\n\x15LaunchNotebookRequest\"\x18\n\x16LaunchNotebookResponse2\x80\x01\n\x1f\x44\x43\x34\x39\x39\x39\x39\x39\x39\x39\x36\x45PME5000Capabilities\x12]\n\x0eLaunchNotebook\x12$.elint.collars.LaunchNotebookRequest\x1a%.elint.collars.LaunchNotebookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.collars.DC499999996_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DC499999996']._serialized_start=90
  _globals['_DC499999996']._serialized_end=305
  _globals['_JUPYTERNOTEBOOK']._serialized_start=307
  _globals['_JUPYTERNOTEBOOK']._serialized_end=336
  _globals['_LAUNCHNOTEBOOKREQUEST']._serialized_start=338
  _globals['_LAUNCHNOTEBOOKREQUEST']._serialized_end=361
  _globals['_LAUNCHNOTEBOOKRESPONSE']._serialized_start=363
  _globals['_LAUNCHNOTEBOOKRESPONSE']._serialized_end=387
  _globals['_DC499999996EPME5000CAPABILITIES']._serialized_start=390
  _globals['_DC499999996EPME5000CAPABILITIES']._serialized_end=518
# @@protoc_insertion_point(module_scope)
