# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/collars/DC499999995.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.collars import DC499999999_pb2 as ethos_dot_elint_dot_collars_dot_DC499999999__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ethos/elint/collars/DC499999995.proto\x12\relint.collars\x1a%ethos/elint/collars/DC499999999.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n\x0b\x44\x43\x34\x39\x39\x39\x39\x39\x39\x39\x35\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12<\n\x12monthly_deployment\x18\x04 \x01(\x0b\x32 .elint.collars.MonthlyDeployment\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\x11MonthlyDeployment\x12\n\n\x02id\x18\x01 \x01(\t\"E\n\x14\x44\x65ployMonthlyRequest\x12-\n\ndeployment\x18\x01 \x01(\x0b\x32\x19.elint.collars.Deployment\"\x17\n\x15\x44\x65ployMonthlyResponse2}\n\x1f\x44\x43\x34\x39\x39\x39\x39\x39\x39\x39\x35\x45PME5000Capabilities\x12Z\n\rDeployMonthly\x12#.elint.collars.DeployMonthlyRequest\x1a$.elint.collars.DeployMonthlyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.collars.DC499999995_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DC499999995']._serialized_start=129
  _globals['_DC499999995']._serialized_end=347
  _globals['_MONTHLYDEPLOYMENT']._serialized_start=349
  _globals['_MONTHLYDEPLOYMENT']._serialized_end=380
  _globals['_DEPLOYMONTHLYREQUEST']._serialized_start=382
  _globals['_DEPLOYMONTHLYREQUEST']._serialized_end=451
  _globals['_DEPLOYMONTHLYRESPONSE']._serialized_start=453
  _globals['_DEPLOYMONTHLYRESPONSE']._serialized_end=476
  _globals['_DC499999995EPME5000CAPABILITIES']._serialized_start=478
  _globals['_DC499999995EPME5000CAPABILITIES']._serialized_end=603
# @@protoc_insertion_point(module_scope)
