# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/collars/DC499999994_caps.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_service_pb2 as ethos_dot_elint_dot_entities_dot_space__service__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__pb2.google.protobuf.timestamp_pb2
from ethos.elint.collars import DC499999994_pb2 as ethos_dot_elint_dot_collars_dot_DC499999994__pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.knowledge.space_knowledge import access_space_knowledge_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge_dot_access__space__knowledge__pb2
from ethos.elint.services.product.product.space_product_domain import access_space_product_domain_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product__domain_dot_access__space__product__domain__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*ethos/elint/collars/DC499999994_caps.proto\x12\relint.collars\x1a(ethos/elint/entities/space_service.proto\x1a%ethos/elint/collars/DC499999994.proto\x1a\"ethos/elint/entities/generic.proto\x1aSethos/elint/services/product/knowledge/space_knowledge/access_space_knowledge.proto\x1a[ethos/elint/services/product/product/space_product_domain/access_space_product_domain.proto\"\x9b\x02\n\x17\x41uthWithSkincareProduct\x12\x64\n\x08spd_auth\x18\x01 \x01(\x0b\x32R.elint.services.product.product.domain.SpaceProductDomainServicesAccessAuthDetails\x12`\n\x07sk_auth\x18\x02 \x01(\x0b\x32O.elint.services.product.knowledge.space.SpaceKnowledgeServicesAccessAuthDetails\x12\x38\n\x10skincare_product\x18\x0b \x01(\x0b\x32\x1e.elint.collars.SkincareProduct\"l\n\x13RepeatedDC499999994\x12(\n\x04meta\x18\x01 \x01(\x0b\x32\x1a.elint.entity.ResponseMeta\x12+\n\x07\x63ollars\x18\x02 \x03(\x0b\x32\x1a.elint.collars.DC499999994\"\xec\x01\n\x13SPDAuthWithCollarID\x12`\n\x04\x61uth\x18\x01 \x01(\x0b\x32R.elint.services.product.product.domain.SpaceProductDomainServicesAccessAuthDetails\x12`\n\x07sk_auth\x18\x02 \x01(\x0b\x32O.elint.services.product.knowledge.space.SpaceKnowledgeServicesAccessAuthDetails\x12\x11\n\tcollar_id\x18\x0b \x01(\t2\x84\x03\n\x1f\x44\x43\x34\x39\x39\x39\x39\x39\x39\x39\x34\x45PME5000Capabilities\x12L\n\x06\x43reate\x12&.elint.collars.AuthWithSkincareProduct\x1a\x1a.elint.entity.ResponseMeta\x12~\n\x04List\x12R.elint.services.product.product.domain.SpaceProductDomainServicesAccessAuthDetails\x1a\".elint.collars.RepeatedDC499999994\x12\x45\n\x03Get\x12\".elint.collars.SPDAuthWithCollarID\x1a\x1a.elint.collars.DC499999994\x12L\n\x06\x44\x65lete\x12&.elint.collars.AuthWithSkincareProduct\x1a\x1a.elint.entity.ResponseMetab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.collars.DC499999994_caps_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUTHWITHSKINCAREPRODUCT']._serialized_start=357
  _globals['_AUTHWITHSKINCAREPRODUCT']._serialized_end=640
  _globals['_REPEATEDDC499999994']._serialized_start=642
  _globals['_REPEATEDDC499999994']._serialized_end=750
  _globals['_SPDAUTHWITHCOLLARID']._serialized_start=753
  _globals['_SPDAUTHWITHCOLLARID']._serialized_end=989
  _globals['_DC499999994EPME5000CAPABILITIES']._serialized_start=992
  _globals['_DC499999994EPME5000CAPABILITIES']._serialized_end=1380
# @@protoc_insertion_point(module_scope)
