# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/space/access_space.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_pb2 as ethos_dot_elint_dot_entities_dot_space__pb2
from ethos.elint.services.product.identity.account import access_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2
from ethos.elint.services.product.identity.account_assistant import access_account_assistant_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account__assistant_dot_access__account__assistant__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>ethos/elint/services/product/identity/space/access_space.proto\x12%elint.services.product.identity.space\x1a\"ethos/elint/entities/generic.proto\x1a ethos/elint/entities/space.proto\x1a\x42\x65thos/elint/services/product/identity/account/access_account.proto\x1aVethos/elint/services/product/identity/account_assistant/access_account_assistant.proto\"\xd8\x01\n\x18SpaceAccessTokenResponse\x12q\n\"space_services_access_auth_details\x18\x01 \x01(\x0b\x32\x45.elint.services.product.identity.space.SpaceServicesAccessAuthDetails\x12\"\n\x1aspace_services_access_done\x18\x02 \x01(\x08\x12%\n\x1dspace_services_access_message\x18\x03 \x01(\t\"~\n\x1dValidateSpaceServicesResponse\x12,\n$space_service_access_validation_done\x18\x01 \x01(\x08\x12/\n\'space_service_access_validation_message\x18\x02 \x01(\t\"\xd8\x01\n\x1eSpaceServicesAccessAuthDetails\x12\"\n\x05space\x18\x01 \x01(\x0b\x32\x13.elint.entity.Space\x12`\n+space_services_access_session_token_details\x18\x02 \x01(\x0b\x32+.elint.entity.PersistentSessionTokenDetails\x12\x30\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x9c\x04\n\x12\x41\x63\x63\x65ssSpaceService\x12\xa0\x01\n\x10SpaceAccessToken\x12I.elint.services.product.identity.account.AccountServicesAccessAuthDetails\x1a?.elint.services.product.identity.space.SpaceAccessTokenResponse\"\x00\x12\xb9\x01\n\x16\x41ssistSpaceAccessToken\x12\\.elint.services.product.identity.account.assistant.AccountAssistantServicesAccessAuthDetails\x1a?.elint.services.product.identity.space.SpaceAccessTokenResponse\"\x00\x12\xa6\x01\n\x15ValidateSpaceServices\x12\x45.elint.services.product.identity.space.SpaceServicesAccessAuthDetails\x1a\x44.elint.services.product.identity.space.ValidateSpaceServicesResponse\"\x00\x42$\n com.ethos.elint.services.productP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.space.access_space_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.ethos.elint.services.productP\001'
  _globals['_SPACEACCESSTOKENRESPONSE']._serialized_start=332
  _globals['_SPACEACCESSTOKENRESPONSE']._serialized_end=548
  _globals['_VALIDATESPACESERVICESRESPONSE']._serialized_start=550
  _globals['_VALIDATESPACESERVICESRESPONSE']._serialized_end=676
  _globals['_SPACESERVICESACCESSAUTHDETAILS']._serialized_start=679
  _globals['_SPACESERVICESACCESSAUTHDETAILS']._serialized_end=895
  _globals['_ACCESSSPACESERVICE']._serialized_start=898
  _globals['_ACCESSSPACESERVICE']._serialized_end=1438
# @@protoc_insertion_point(module_scope)
