# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/space/create_space.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_pb2 as ethos_dot_elint_dot_entities_dot_space__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>ethos/elint/services/product/identity/space/create_space.proto\x12%elint.services.product.identity.space\x1a\"ethos/elint/entities/account.proto\x1a\"ethos/elint/entities/generic.proto\x1a ethos/elint/entities/space.proto\"\xfd\x01\n\x19\x43reateAccountSpaceRequest\x12&\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x15.elint.entity.Account\x12\x46\n\x18space_accessibility_type\x18\x04 \x01(\x0e\x32$.elint.entity.SpaceAccessibilityType\x12>\n\x14space_isolation_type\x18\x05 \x01(\x0e\x32 .elint.entity.SpaceIsolationType\x12\x30\n\x0crequested_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x89\x01\n\x1a\x43reateAccountSpaceResponse\x12\"\n\x05space\x18\x01 \x01(\x0b\x32\x13.elint.entity.Space\x12!\n\x19\x63reate_account_space_done\x18\x02 \x01(\x08\x12$\n\x1c\x63reate_account_space_message\x18\x03 \x01(\t2\xb2\x01\n\x12\x43reateSpaceService\x12\x9b\x01\n\x12\x43reateAccountSpace\x12@.elint.services.product.identity.space.CreateAccountSpaceRequest\x1a\x41.elint.services.product.identity.space.CreateAccountSpaceResponse\"\x00\x42$\n com.ethos.elint.services.productP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.space.create_space_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.ethos.elint.services.productP\001'
  _globals['_CREATEACCOUNTSPACEREQUEST']._serialized_start=212
  _globals['_CREATEACCOUNTSPACEREQUEST']._serialized_end=465
  _globals['_CREATEACCOUNTSPACERESPONSE']._serialized_start=468
  _globals['_CREATEACCOUNTSPACERESPONSE']._serialized_end=605
  _globals['_CREATESPACESERVICE']._serialized_start=608
  _globals['_CREATESPACESERVICE']._serialized_end=786
# @@protoc_insertion_point(module_scope)
