# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/conversation/message/account_assistant/send_account_assistant_message.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from ethos.elint.entities import account_assistant_pb2 as ethos_dot_elint_dot_entities_dot_account__assistant__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__assistant__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__assistant__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.account_assistant import access_account_assistant_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account__assistant_dot_access__account__assistant__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nhethos/elint/services/product/conversation/message/account_assistant/send_account_assistant_message.proto\x12=elint.services.product.conversation.message.account.assistant\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a,ethos/elint/entities/account_assistant.proto\x1aVethos/elint/services/product/identity/account_assistant/access_account_assistant.proto\"\xea\x03\n\x11MessageForAccount\x12y\n\x13\x61\x63\x63\x65ss_auth_details\x18\x01 \x01(\x0b\x32\\.elint.services.product.identity.account.assistant.AccountAssistantServicesAccessAuthDetails\x12I\n\x11\x63onnected_account\x18\x02 \x01(\x0b\x32..elint.entity.AccountAssistantConnectedAccount\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x1f\n\x17message_source_space_id\x18\x04 \x01(\t\x12$\n\x1cmessage_source_space_type_id\x18\x05 \x01(\t\x12&\n\x1emessage_source_space_domain_id\x18\x06 \x01(\t\x12*\n\"message_source_space_domain_action\x18\x07 \x01(\x05\x12\x35\n-message_source_space_domain_action_context_id\x18\x08 \x01(\t\x12,\n\x0emessage_source\x18\t \x03(\x0b\x32\x14.google.protobuf.Any\"\xa7\x01\n\x15MessageForAccountSent\x12\x1f\n\x17\x61\x63\x63ount_sent_message_id\x18\x01 \x01(\t\x12\x0f\n\x07is_sent\x18\x02 \x01(\x08\x12+\n\x07sent_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0breceived_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xe7\x01\n\"SendAccountAssistantMessageService\x12\xc0\x01\n\x14SendMessageToAccount\x12P.elint.services.product.conversation.message.account.assistant.MessageForAccount\x1aT.elint.services.product.conversation.message.account.assistant.MessageForAccountSent\"\x00P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.conversation.message.account_assistant.send_account_assistant_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGEFORACCOUNT']._serialized_start=366
  _globals['_MESSAGEFORACCOUNT']._serialized_end=856
  _globals['_MESSAGEFORACCOUNTSENT']._serialized_start=859
  _globals['_MESSAGEFORACCOUNTSENT']._serialized_end=1026
  _globals['_SENDACCOUNTASSISTANTMESSAGESERVICE']._serialized_start=1029
  _globals['_SENDACCOUNTASSISTANTMESSAGESERVICE']._serialized_end=1260
# @@protoc_insertion_point(module_scope)
