# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/associate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import organisation_pb2 as ethos_dot_elint_dot_entities_dot_organisation__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_organisation__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_organisation__pb2.google.protobuf.timestamp_pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ethos/elint/entities/associate.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"ethos/elint/entities/account.proto\x1a\'ethos/elint/entities/organisation.proto\"\xfc\x02\n\tAssociate\x12\x31\n\x12\x61ssociated_account\x18\x01 \x01(\x0b\x32\x15.elint.entity.Account\x12;\n\x17\x61ssociated_organisation\x18\x02 \x01(\x0b\x32\x1a.elint.entity.Organisation\x12\x14\n\x0c\x61ssociate_id\x18\x03 \x01(\x05\x12\x35\n\x0f\x61ssociate_level\x18\x04 \x01(\x0e\x32\x1c.elint.entity.AssociateLevel\x12?\n\x14\x61ssociate_department\x18\x05 \x01(\x0e\x32!.elint.entity.AssociateDepartment\x12\x1d\n\x15\x61ssociate_designation\x18\x06 \x01(\t\x12\x1f\n\x17reports_to_associate_id\x18\x07 \x01(\x05\x12\x31\n\rassociated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp*^\n\x0e\x41ssociateLevel\x12\x0b\n\x07LEVEL_0\x10\x00\x12\x0b\n\x07LEVEL_1\x10\x01\x12\x0b\n\x07LEVEL_2\x10\x02\x12\x0b\n\x07LEVEL_3\x10\x03\x12\x0b\n\x07LEVEL_4\x10\x04\x12\x0b\n\x07LEVEL_5\x10\x05*\x99\x01\n\x13\x41ssociateDepartment\x12\x0e\n\nACCOUNTING\x10\x00\x12\x12\n\x0eHUMAN_RESOURCE\x10\x01\x12\x1a\n\x16INFORMATION_TECHNOLOGY\x10\x02\x12\r\n\tLOGISTICS\x10\x03\x12\r\n\tMARKETING\x10\x04\x12\x0e\n\nPRODUCTION\x10\x05\x12\t\n\x05SALES\x10\x06\x12\t\n\x05WORKS\x10\x07\x42 \n\x0c\x65lint.entityB\x0e\x41ssociateProtoP\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.associate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\016AssociateProtoP\001'
  _ASSOCIATELEVEL._serialized_start=547
  _ASSOCIATELEVEL._serialized_end=641
  _ASSOCIATEDEPARTMENT._serialized_start=644
  _ASSOCIATEDEPARTMENT._serialized_end=797
  _ASSOCIATE._serialized_start=165
  _ASSOCIATE._serialized_end=545
# @@protoc_insertion_point(module_scope)
