# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/generic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"ethos/elint/entities/generic.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n\x1dPersistentSessionTokenDetails\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x15\n\rsession_scope\x18\x02 \x01(\t\x12\x30\n\x0cgenerated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0clast_used_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nvalid_till\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xae\x01\n\x1cTemporarySessionTokenDetails\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x15\n\rsession_scope\x18\x02 \x01(\t\x12\x30\n\x0cgenerated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nvalid_till\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xbb\x01\n\x16PersistentTokenDetails\x12\r\n\x05token\x18\x01 \x01(\t\x12\x30\n\x0cgenerated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0clast_used_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nvalid_till\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x88\x01\n\x15TemporaryTokenDetails\x12\r\n\x05token\x18\x01 \x01(\t\x12\x30\n\x0cgenerated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nvalid_till\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n\x0cResponseMeta\x12\x11\n\tmeta_done\x18\x01 \x01(\x08\x12\x14\n\x0cmeta_message\x18\x02 \x01(\t*E\n\x0bPictureSize\x12\x07\n\x03x20\x10\x00\x12\x07\n\x03x29\x10\x01\x12\x07\n\x03x40\x10\x02\x12\x07\n\x03x60\x10\x03\x12\x07\n\x03x76\x10\x04\x12\t\n\x05x83p5\x10\x05*&\n\x0cPictureScale\x12\x06\n\x02x1\x10\x00\x12\x06\n\x02x2\x10\x01\x12\x06\n\x02x3\x10\x02\x42\x1e\n\x0c\x65lint.entityB\x0cGenericProtoP\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.generic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\014GenericProtoP\001'
  _PICTURESIZE._serialized_start=876
  _PICTURESIZE._serialized_end=945
  _PICTURESCALE._serialized_start=947
  _PICTURESCALE._serialized_end=985
  _PERSISTENTSESSIONTOKENDETAILS._serialized_start=86
  _PERSISTENTSESSIONTOKENDETAILS._serialized_end=311
  _TEMPORARYSESSIONTOKENDETAILS._serialized_start=314
  _TEMPORARYSESSIONTOKENDETAILS._serialized_end=488
  _PERSISTENTTOKENDETAILS._serialized_start=491
  _PERSISTENTTOKENDETAILS._serialized_end=678
  _TEMPORARYTOKENDETAILS._serialized_start=681
  _TEMPORARYTOKENDETAILS._serialized_end=817
  _RESPONSEMETA._serialized_start=819
  _RESPONSEMETA._serialized_end=874
# @@protoc_insertion_point(module_scope)
