# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/galaxy.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import universe_pb2 as ethos_dot_elint_dot_entities_dot_universe__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_universe__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_universe__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ethos/elint/entities/galaxy.proto\x12\x0c\x65lint.entity\x1a#ethos/elint/entities/universe.proto\"\xf4\x01\n\x06Galaxy\x12\x11\n\tgalaxy_id\x18\x01 \x01(\t\x12\x13\n\x0bgalaxy_name\x18\x02 \x01(\t\x12(\n\x08universe\x18\x03 \x01(\x0b\x32\x16.elint.entity.Universe\x12\x35\n\x11galaxy_created_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11galaxy_updated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06\x64omain\x18\x06 \x01(\t\x12\x1a\n\x12galaxy_description\x18\x07 \x01(\t*]\n\x12OpenGalaxyTierEnum\x12\r\n\tFREE_TIER\x10\x00\x12\x0e\n\nBASIC_TIER\x10\x01\x12\x11\n\rSTANDARD_TIER\x10\x02\x12\x15\n\x11PROFESSIONAL_TIER\x10\x03\x42\x1d\n\x0c\x65lint.entityB\x0bGalaxyProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.galaxy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014elint.entityB\013GalaxyProtoP\001'
  _globals['_OPENGALAXYTIERENUM']._serialized_start=335
  _globals['_OPENGALAXYTIERENUM']._serialized_end=428
  _globals['_GALAXY']._serialized_start=89
  _globals['_GALAXY']._serialized_end=333
# @@protoc_insertion_point(module_scope)
