# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/space_service_domain.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.entities import space_service_pb2 as ethos_dot_elint_dot_entities_dot_space__service__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__pb2.google.protobuf.timestamp_pb2
from ethos.elint.collars import DC500000000_pb2 as ethos_dot_elint_dot_collars_dot_DC500000000__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC500000000__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_collars_dot_DC500000000__pb2.google.protobuf.timestamp_pb2
from ethos.elint.collars import DC499999999_pb2 as ethos_dot_elint_dot_collars_dot_DC499999999__pb2
from ethos.elint.collars import DC499999998_pb2 as ethos_dot_elint_dot_collars_dot_DC499999998__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ethos/elint/entities/space_service_domain.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(ethos/elint/entities/space_service.proto\x1a%ethos/elint/collars/DC500000000.proto\x1a%ethos/elint/collars/DC499999999.proto\x1a%ethos/elint/collars/DC499999998.proto\"\x9f\x03\n\x12SpaceServiceDomain\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bis_isolated\x18\x04 \x01(\x08\x12\x31\n\rspace_service\x18\x05 \x01(\x0b\x32\x1a.elint.entity.SpaceService\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0flast_updated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x0b\x64\x63\x35\x30\x30\x30\x30\x30\x30\x30\x30\x18\x80\xca\xb5\xee\x01 \x01(\x0b\x32\x1a.elint.collars.DC500000000H\x00\x12\x35\n\x0b\x64\x63\x34\x39\x39\x39\x39\x39\x39\x39\x39\x18\xff\xc9\xb5\xee\x01 \x01(\x0b\x32\x1a.elint.collars.DC499999999H\x00\x12\x35\n\x0b\x64\x63\x34\x39\x39\x39\x39\x39\x39\x39\x38\x18\xfe\xc9\xb5\xee\x01 \x01(\x0b\x32\x1a.elint.collars.DC499999998H\x00\x42\x08\n\x06\x63ollarB)\n\x0c\x65lint.entityB\x17SpaceServiceDomainProtoP\x01P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.space_service_domain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014elint.entityB\027SpaceServiceDomainProtoP\001'
  _globals['_SPACESERVICEDOMAIN']._serialized_start=258
  _globals['_SPACESERVICEDOMAIN']._serialized_end=673
# @@protoc_insertion_point(module_scope)
