# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.service.space_service_domain import access_space_service_domain_pb2 as ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2


class AccessSpaceServiceDomainServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpaceServiceDomainAccessToken = channel.unary_unary(
                '/elint.services.product.service.domain.AccessSpaceServiceDomainService/SpaceServiceDomainAccessToken',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainAccessTokenRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainAccessTokenResponse.FromString,
                )
        self.ValidateSpaceServiceDomainServices = channel.unary_unary(
                '/elint.services.product.service.domain.AccessSpaceServiceDomainService/ValidateSpaceServiceDomainServices',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.ValidateSpaceServiceDomainServicesResponse.FromString,
                )


class AccessSpaceServiceDomainServiceServicer(object):
    """Service Definitions
    """

    def SpaceServiceDomainAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSpaceServiceDomainServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessSpaceServiceDomainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpaceServiceDomainAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.SpaceServiceDomainAccessToken,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainAccessTokenRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainAccessTokenResponse.SerializeToString,
            ),
            'ValidateSpaceServiceDomainServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSpaceServiceDomainServices,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.ValidateSpaceServiceDomainServicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.service.domain.AccessSpaceServiceDomainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessSpaceServiceDomainService(object):
    """Service Definitions
    """

    @staticmethod
    def SpaceServiceDomainAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.domain.AccessSpaceServiceDomainService/SpaceServiceDomainAccessToken',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainAccessTokenRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateSpaceServiceDomainServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.domain.AccessSpaceServiceDomainService/ValidateSpaceServiceDomainServices',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.SpaceServiceDomainServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service__domain_dot_access__space__service__domain__pb2.ValidateSpaceServiceDomainServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
