# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/service/space_service_domain/create_space_service_domain.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_service_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__service__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__domain__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.service.space_service import access_space_service_pb2 as ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2
from ethos.elint.collars import DC499999998_pb2 as ethos_dot_elint_dot_collars_dot_DC499999998__pb2
from ethos.elint.collars import DC499999999_pb2 as ethos_dot_elint_dot_collars_dot_DC499999999__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[ethos/elint/services/product/service/space_service_domain/create_space_service_domain.proto\x12%elint.services.product.service.domain\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"ethos/elint/entities/generic.proto\x1a/ethos/elint/entities/space_service_domain.proto\x1aMethos/elint/services/product/service/space_service/access_space_service.proto\x1a%ethos/elint/collars/DC499999998.proto\x1a%ethos/elint/collars/DC499999999.proto\"\xe1\x01\n\x1b\x43reateDC499999998SSDRequest\x12Y\n\x04\x61uth\x18\x01 \x01(\x0b\x32K.elint.services.product.service.space.SpaceServiceServicesAccessAuthDetails\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bis_isolated\x18\x04 \x01(\x08\x12/\n\x0b\x64\x63\x34\x39\x39\x39\x39\x39\x39\x39\x38\x18\x05 \x01(\x0b\x32\x1a.elint.collars.DC499999998\"\xe1\x01\n\x1b\x43reateDC499999999SSDRequest\x12Y\n\x04\x61uth\x18\x01 \x01(\x0b\x32K.elint.services.product.service.space.SpaceServiceServicesAccessAuthDetails\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bis_isolated\x18\x04 \x01(\x08\x12/\n\x0b\x64\x63\x34\x39\x39\x39\x39\x39\x39\x39\x39\x18\x05 \x01(\x0b\x32\x1a.elint.collars.DC4999999992\x8f\x02\n\x1f\x43reateSpaceServiceDomainService\x12u\n\x11\x43reateDC499999998\x12\x42.elint.services.product.service.domain.CreateDC499999998SSDRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x12u\n\x11\x43reateDC499999999\x12\x42.elint.services.product.service.domain.CreateDC499999999SSDRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.service.space_service_domain.create_space_service_domain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEDC499999998SSDREQUEST']._serialized_start=410
  _globals['_CREATEDC499999998SSDREQUEST']._serialized_end=635
  _globals['_CREATEDC499999999SSDREQUEST']._serialized_start=638
  _globals['_CREATEDC499999999SSDREQUEST']._serialized_end=863
  _globals['_CREATESPACESERVICEDOMAINSERVICE']._serialized_start=866
  _globals['_CREATESPACESERVICEDOMAINSERVICE']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
