# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/machine/discover_machine.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import machine_pb2 as ethos_dot_elint_dot_entities_dot_machine__pb2
from ethos.elint.services.product.identity.account import access_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDethos/elint/services/product/identity/machine/discover_machine.proto\x12\'elint.services.product.identity.machine\x1a\"ethos/elint/entities/generic.proto\x1a\"ethos/elint/entities/machine.proto\x1a\x42\x65thos/elint/services/product/identity/account/access_account.proto\"u\n\x17ListAllMachinesResponse\x12\'\n\x08machines\x18\x01 \x03(\x0b\x32\x15.elint.entity.Machine\x12\x31\n\rresponse_meta\x18\x02 \x01(\x0b\x32\x1a.elint.entity.ResponseMeta2\xbb\x01\n\x16\x44iscoverMachineService\x12\xa0\x01\n\x0fListAllMachines\x12I.elint.services.product.identity.account.AccountServicesAccessAuthDetails\x1a@.elint.services.product.identity.machine.ListAllMachinesResponse\"\x00\x42$\n com.ethos.elint.services.productP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.machine.discover_machine_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.ethos.elint.services.productP\001'
  _globals['_LISTALLMACHINESRESPONSE']._serialized_start=253
  _globals['_LISTALLMACHINESRESPONSE']._serialized_end=370
  _globals['_DISCOVERMACHINESERVICE']._serialized_start=373
  _globals['_DISCOVERMACHINESERVICE']._serialized_end=560
# @@protoc_insertion_point(module_scope)
