# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/galaxy/read_galaxy.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import universe_pb2 as ethos_dot_elint_dot_entities_dot_universe__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_universe__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_universe__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import galaxy_pb2 as ethos_dot_elint_dot_entities_dot_galaxy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>ethos/elint/services/product/identity/galaxy/read_galaxy.proto\x12&elint.services.product.identity.galaxy\x1a\"ethos/elint/entities/account.proto\x1a#ethos/elint/entities/universe.proto\x1a!ethos/elint/entities/galaxy.proto\"&\n\x11ReadGalaxyRequest\x12\x11\n\tgalaxy_id\x18\x01 \x01(\t\":\n\x12ReadGalaxyResponse\x12$\n\x06galaxy\x18\x01 \x01(\x0b\x32\x14.elint.entity.Galaxy2\x99\x01\n\x11ReadGalaxyService\x12\x83\x01\n\nReadGalaxy\x12\x39.elint.services.product.identity.galaxy.ReadGalaxyRequest\x1a:.elint.services.product.identity.galaxy.ReadGalaxyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.galaxy.read_galaxy_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READGALAXYREQUEST']._serialized_start=214
  _globals['_READGALAXYREQUEST']._serialized_end=252
  _globals['_READGALAXYRESPONSE']._serialized_start=254
  _globals['_READGALAXYRESPONSE']._serialized_end=312
  _globals['_READGALAXYSERVICE']._serialized_start=315
  _globals['_READGALAXYSERVICE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
