# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.galaxy import update_galaxy_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2


class UpdateGalaxyServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateGalaxy = channel.unary_unary(
                '/elint.services.product.identity.galaxy.UpdateGalaxyService/UpdateGalaxy',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2.UpdateGalaxyRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2.UpdateGalaxyResponse.FromString,
                )


class UpdateGalaxyServiceServicer(object):
    """Service Definitions
    """

    def UpdateGalaxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateGalaxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateGalaxy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGalaxy,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2.UpdateGalaxyRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2.UpdateGalaxyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.galaxy.UpdateGalaxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpdateGalaxyService(object):
    """Service Definitions
    """

    @staticmethod
    def UpdateGalaxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.galaxy.UpdateGalaxyService/UpdateGalaxy',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2.UpdateGalaxyRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_galaxy_dot_update__galaxy__pb2.UpdateGalaxyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
