# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/product/space_product/access_space_product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_product_pb2 as ethos_dot_elint_dot_entities_dot_space__product__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__product__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__product__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.space import access_space_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMethos/elint/services/product/product/space_product/access_space_product.proto\x12$elint.services.product.product.space\x1a\"ethos/elint/entities/generic.proto\x1a\"ethos/elint/entities/account.proto\x1a(ethos/elint/entities/space_product.proto\x1a>ethos/elint/services/product/identity/space/access_space.proto\"\xfd\x01\n\x1fSpaceProductAccessTokenResponse\x12\x7f\n*space_product_services_access_auth_details\x18\x01 \x01(\x0b\x32K.elint.services.product.product.space.SpaceProductServicesAccessAuthDetails\x12*\n\"space_product_services_access_done\x18\x02 \x01(\x08\x12-\n%space_product_services_access_message\x18\x03 \x01(\t\"\x97\x01\n$ValidateSpaceProductServicesResponse\x12\x35\n-space_product_services_access_validation_done\x18\x01 \x01(\x08\x12\x38\n0space_product_services_access_validation_message\x18\x02 \x01(\t\"\xf6\x01\n%SpaceProductServicesAccessAuthDetails\x12\x31\n\rspace_product\x18\x01 \x01(\x0b\x32\x1a.elint.entity.SpaceProduct\x12h\n3space_product_services_access_session_token_details\x18\x02 \x01(\x0b\x32+.elint.entity.PersistentSessionTokenDetails\x12\x30\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x83\x03\n\x19\x41\x63\x63\x65ssSpaceProductService\x12\xa9\x01\n\x17SpaceProductAccessToken\x12\x45.elint.services.product.identity.space.SpaceServicesAccessAuthDetails\x1a\x45.elint.services.product.product.space.SpaceProductAccessTokenResponse\"\x00\x12\xb9\x01\n\x1cValidateSpaceProductServices\x12K.elint.services.product.product.space.SpaceProductServicesAccessAuthDetails\x1aJ.elint.services.product.product.space.ValidateSpaceProductServicesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.product.space_product.access_space_product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPACEPRODUCTACCESSTOKENRESPONSE']._serialized_start=298
  _globals['_SPACEPRODUCTACCESSTOKENRESPONSE']._serialized_end=551
  _globals['_VALIDATESPACEPRODUCTSERVICESRESPONSE']._serialized_start=554
  _globals['_VALIDATESPACEPRODUCTSERVICESRESPONSE']._serialized_end=705
  _globals['_SPACEPRODUCTSERVICESACCESSAUTHDETAILS']._serialized_start=708
  _globals['_SPACEPRODUCTSERVICESACCESSAUTHDETAILS']._serialized_end=954
  _globals['_ACCESSSPACEPRODUCTSERVICE']._serialized_start=957
  _globals['_ACCESSSPACEPRODUCTSERVICE']._serialized_end=1344
# @@protoc_insertion_point(module_scope)
