# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.space import access_space_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2
from ethos.elint.services.product.product.space_product import access_space_product_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2


class AccessSpaceProductServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpaceProductAccessToken = channel.unary_unary(
                '/elint.services.product.product.space.AccessSpaceProductService/SpaceProductAccessToken',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2.SpaceServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.SpaceProductAccessTokenResponse.FromString,
                )
        self.ValidateSpaceProductServices = channel.unary_unary(
                '/elint.services.product.product.space.AccessSpaceProductService/ValidateSpaceProductServices',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.SpaceProductServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.ValidateSpaceProductServicesResponse.FromString,
                )


class AccessSpaceProductServiceServicer(object):
    """Service Definitions
    """

    def SpaceProductAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSpaceProductServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessSpaceProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpaceProductAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.SpaceProductAccessToken,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2.SpaceServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.SpaceProductAccessTokenResponse.SerializeToString,
            ),
            'ValidateSpaceProductServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSpaceProductServices,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.SpaceProductServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.ValidateSpaceProductServicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.product.space.AccessSpaceProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessSpaceProductService(object):
    """Service Definitions
    """

    @staticmethod
    def SpaceProductAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.product.space.AccessSpaceProductService/SpaceProductAccessToken',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2.SpaceServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.SpaceProductAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateSpaceProductServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.product.space.AccessSpaceProductService/ValidateSpaceProductServices',
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.SpaceProductServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2.ValidateSpaceProductServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
