# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/product/space_product/create_space_product.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.services.product.identity.space import access_space_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2
from ethos.elint.services.product.product.space_product import access_space_product_pb2 as ethos_dot_elint_dot_services_dot_product_dot_product_dot_space__product_dot_access__space__product__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMethos/elint/services/product/product/space_product/create_space_product.proto\x12$elint.services.product.product.space\x1a\x1fgoogle/protobuf/timestamp.proto\x1a>ethos/elint/services/product/identity/space/access_space.proto\x1aMethos/elint/services/product/product/space_product/access_space_product.proto\"\xe3\x01\n CreateAccountSpaceProductRequest\x12q\n\"space_services_access_auth_details\x18\x01 \x01(\x0b\x32\x45.elint.services.product.identity.space.SpaceServicesAccessAuthDetails\x12\x1a\n\x12space_product_name\x18\x02 \x01(\t\x12\x30\n\x0crequested_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xfd\x01\n!CreateAccountSpaceProductResponse\x12\x7f\n*space_product_services_access_auth_details\x18\x01 \x01(\x0b\x32K.elint.services.product.product.space.SpaceProductServicesAccessAuthDetails\x12)\n!create_account_space_product_done\x18\x02 \x01(\x08\x12,\n$create_account_space_product_message\x18\x03 \x01(\t2\xcc\x01\n\x19\x43reateSpaceProductService\x12\xae\x01\n\x19\x43reateAccountSpaceProduct\x12\x46.elint.services.product.product.space.CreateAccountSpaceProductRequest\x1aG.elint.services.product.product.space.CreateAccountSpaceProductResponse\"\x00P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.product.space_product.create_space_product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEACCOUNTSPACEPRODUCTREQUEST']._serialized_start=296
  _globals['_CREATEACCOUNTSPACEPRODUCTREQUEST']._serialized_end=523
  _globals['_CREATEACCOUNTSPACEPRODUCTRESPONSE']._serialized_start=526
  _globals['_CREATEACCOUNTSPACEPRODUCTRESPONSE']._serialized_end=779
  _globals['_CREATESPACEPRODUCTSERVICE']._serialized_start=782
  _globals['_CREATESPACEPRODUCTSERVICE']._serialized_end=986
# @@protoc_insertion_point(module_scope)
