# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gramx/fifty/zero/ethos/identity/multiverse/epme/1001.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:gramx/fifty/zero/ethos/identity/multiverse/epme/1001.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x02\n\x08\x45PME1001\x12\x1c\n\x14\x61\x63\x63ount_analytics_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12!\n\x19\x61\x63\x63ount_personal_email_id\x18\x03 \x01(\t\x12\x1d\n\x15\x61\x63\x63ount_work_email_id\x18\x04 \x01(\t\x12\x1c\n\x14\x61\x63\x63ount_country_code\x18\x05 \x01(\t\x12\x1d\n\x15\x61\x63\x63ount_mobile_number\x18\x06 \x01(\t\x12\x1a\n\x12\x61\x63\x63ount_first_name\x18\x07 \x01(\t\x12\x19\n\x11\x61\x63\x63ount_last_name\x18\x08 \x01(\t\x12\x19\n\x11\x61\x63\x63ount_galaxy_id\x18\t \x01(\t\x12\x34\n\x10\x61\x63\x63ount_birth_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\ncreated_at\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gramx.fifty.zero.ethos.identity.multiverse.epme.1001_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EPME1001._serialized_start=110
  _EPME1001._serialized_end=481
# @@protoc_insertion_point(module_scope)
