# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/ProfileService.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:ethos/elint/services/product/identity/ProfileService.proto\x12%ethos.elint.services.product.identity\"\x1e\n\x0b\x46ilterInput\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"C\n\x0bMeshProfile\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\x86\x01\n\x0eProfileService\x12t\n\nGetProfile\x12\x32.ethos.elint.services.product.identity.FilterInput\x1a\x32.ethos.elint.services.product.identity.MeshProfileB6Z4ethos/elint/services/product/identity;profileserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.identity.ProfileService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4ethos/elint/services/product/identity;profileservice'
  _globals['_FILTERINPUT']._serialized_start=101
  _globals['_FILTERINPUT']._serialized_end=131
  _globals['_MESHPROFILE']._serialized_start=133
  _globals['_MESHPROFILE']._serialized_end=200
  _globals['_PROFILESERVICE']._serialized_start=203
  _globals['_PROFILESERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
