# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/community_collaborator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.entities import community_pb2 as ethos_dot_elint_dot_entities_dot_community__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_community__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_community__pb2.google.protobuf.timestamp_pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ethos/elint/entities/community_collaborator.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$ethos/elint/entities/community.proto\"9\n\x10\x43ollaboratorName\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"J\n\x13\x43ollaboratorContact\x12\x33\n\x0fpersonal_mobile\x18\x01 \x01(\x0b\x32\x1a.elint.entity.MobileNumber\"<\n\x0cMobileNumber\x12\x14\n\x0c\x64ialing_code\x18\x01 \x01(\t\x12\x16\n\x0e\x64ialing_number\x18\x02 \x01(\t\"\x8c\x02\n\x15\x43ommunityCollaborator\x12\x17\n\x0f\x63ollaborator_id\x18\x01 \x01(\t\x12\x39\n\x11\x63ollaborator_name\x18\x02 \x01(\x0b\x32\x1e.elint.entity.CollaboratorName\x12@\n\x15\x63ommunity_domain_code\x18\x03 \x01(\x0e\x32!.elint.entity.CommunityDomainCode\x12?\n\x14\x63ollaborator_contact\x18\x04 \x01(\x0b\x32!.elint.entity.CollaboratorContact\x12\x1c\n\x14is_core_collaborator\x18\x05 \x01(\x08\x42,\n\x0c\x65lint.entityB\x1a\x43ommunityCollaboratorProtoP\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.community_collaborator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\032CommunityCollaboratorProtoP\001'
  _COLLABORATORNAME._serialized_start=138
  _COLLABORATORNAME._serialized_end=195
  _COLLABORATORCONTACT._serialized_start=197
  _COLLABORATORCONTACT._serialized_end=271
  _MOBILENUMBER._serialized_start=273
  _MOBILENUMBER._serialized_end=333
  _COMMUNITYCOLLABORATOR._serialized_start=336
  _COMMUNITYCOLLABORATOR._serialized_end=604
# @@protoc_insertion_point(module_scope)
