# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/organisation.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import community_pb2 as ethos_dot_elint_dot_entities_dot_community__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_community__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_community__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import galaxy_pb2 as ethos_dot_elint_dot_entities_dot_galaxy__pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'ethos/elint/entities/organisation.proto\x12\x0c\x65lint.entity\x1a\"ethos/elint/entities/account.proto\x1a$ethos/elint/entities/community.proto\x1a!ethos/elint/entities/galaxy.proto\x1a\"ethos/elint/entities/generic.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x03\n\x0cOrganisation\x12\x14\n\x0c\x61nalytics_id\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12,\n\x04name\x18\x03 \x01(\x0b\x32\x1e.elint.entity.OrganisationName\x12$\n\x06galaxy\x18\x04 \x01(\x0b\x32\x14.elint.entity.Galaxy\x12$\n\x05\x61\x64min\x18\x05 \x01(\x0b\x32\x15.elint.entity.Account\x12\x35\n\x14\x61ssociated_community\x18\x06 \x01(\x0b\x32\x17.elint.entity.Community\x12?\n\x0epostal_address\x18\x07 \x01(\x0b\x32\'.elint.entity.OrganisationPostalAddress\x12\x33\n\x0fincorporated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tis_active\x18\t \x01(\x08\x12\x19\n\x11is_billing_active\x18\n \x01(\x08\x12.\n\ncreated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\">\n\x10OrganisationName\x12\x12\n\nlegal_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61ssistant_name\x18\x02 \x01(\t\"\x97\x01\n\x19OrganisationPostalAddress\x12\x16\n\x0e\x61\x64\x64ress_line_1\x18\x01 \x01(\t\x12\x16\n\x0e\x61\x64\x64ress_line_2\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12 \n\x18state_province_or_region\x18\x04 \x01(\t\x12\x1a\n\x12zip_or_postal_code\x18\x05 \x01(\tB#\n\x0c\x65lint.entityB\x11OrganisationProtoP\x01P\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.organisation_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\021OrganisationProtoP\001'
  _ORGANISATION._serialized_start=236
  _ORGANISATION._serialized_end=673
  _ORGANISATIONNAME._serialized_start=675
  _ORGANISATIONNAME._serialized_end=737
  _ORGANISATIONPOSTALADDRESS._serialized_start=740
  _ORGANISATIONPOSTALADDRESS._serialized_end=891
# @@protoc_insertion_point(module_scope)
