# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/space_knowledge_domain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from ethos.elint.entities import space_knowledge_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.google.protobuf.timestamp_pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1ethos/elint/entities/space_knowledge_domain.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\x1a*ethos/elint/entities/space_knowledge.proto\"\xa9\x03\n\x14SpaceKnowledgeDomain\x12!\n\x19space_knowledge_domain_id\x18\x01 \x01(\t\x12#\n\x1bspace_knowledge_domain_name\x18\x02 \x01(\t\x12*\n\"space_knowledge_domain_description\x18\x03 \x01(\t\x12X\n\"space_knowledge_domain_collar_enum\x18\x04 \x01(\x0e\x32,.elint.entity.SpaceKnowledgeDomainCollarEnum\x12\'\n\x1fspace_knowledge_domain_isolated\x18\x05 \x01(\x08\x12\x35\n\x0fspace_knowledge\x18\x06 \x01(\x0b\x32\x1c.elint.entity.SpaceKnowledge\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0flast_updated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xa5\x01\n$SpaceKnowledgeDomainInferringAccount\x12\x1c\n\x14inferring_account_id\x18\x01 \x01(\t\x12\x1a\n\x12space_knowledge_id\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12/\n\x0binferred_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"E\n\x0cRankedAnswer\x12\x12\n\ncontext_id\x18\x01 \x01(\t\x12\x11\n\tpara_rank\x18\x02 \x01(\x02\x12\x0e\n\x06\x61nswer\x18\x03 \x01(\t*\xa7\x02\n\x1eSpaceKnowledgeDomainCollarEnum\x12\x10\n\x0cWHITE_COLLAR\x10\x00\x12\x0f\n\x0b\x42LUE_COLLAR\x10\x01\x12\x0f\n\x0bPINK_COLLAR\x10\x02\x12\x0f\n\x0bGOLD_COLLAR\x10\x03\x12\x0e\n\nRED_COLLAR\x10\x04\x12\x11\n\rPURPLE_COLLAR\x10\x05\x12\x0e\n\nNEW_COLLAR\x10\x06\x12\r\n\tNO_COLLAR\x10\x07\x12\x11\n\rORANGE_COLLAR\x10\x08\x12\x10\n\x0cGREEN_COLLAR\x10\t\x12\x12\n\x0eSCARLET_COLLAR\x10\n\x12\x10\n\x0c\x42ROWN_COLLAR\x10\x0b\x12\x10\n\x0cSTEEL_COLLAR\x10\x0c\x12\x10\n\x0c\x42LACK_COLLAR\x10\r\x12\x0f\n\x0bGREY_COLLAR\x10\x0e\x42+\n\x0c\x65lint.entityB\x19SpaceKnowledgeDomainProtoP\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.space_knowledge_domain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\031SpaceKnowledgeDomainProtoP\001'
  _SPACEKNOWLEDGEDOMAINCOLLARENUM._serialized_start=812
  _SPACEKNOWLEDGEDOMAINCOLLARENUM._serialized_end=1107
  _SPACEKNOWLEDGEDOMAIN._serialized_start=145
  _SPACEKNOWLEDGEDOMAIN._serialized_end=570
  _SPACEKNOWLEDGEDOMAININFERRINGACCOUNT._serialized_start=573
  _SPACEKNOWLEDGEDOMAININFERRINGACCOUNT._serialized_end=738
  _RANKEDANSWER._serialized_start=740
  _RANKEDANSWER._serialized_end=809
# @@protoc_insertion_point(module_scope)
