# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/space_knowledge_domain_file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_knowledge_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6ethos/elint/entities/space_knowledge_domain_file.proto\x12\x0c\x65lint.entity\x1a\x31\x65thos/elint/entities/space_knowledge_domain.proto\"5\n\x07\x46ileTag\x12\x13\n\x0b\x66ile_tag_id\x18\x01 \x01(\t\x12\x15\n\rfile_tag_name\x18\x02 \x01(\t\"\x87\x04\n\x18SpaceKnowledgeDomainFile\x12(\n space_knowledge_domain_file_name\x18\x01 \x01(\t\x12(\n space_knowledge_domain_file_size\x18\x02 \x01(\x05\x12&\n\x1espace_knowledge_domain_file_id\x18\x03 \x01(\t\x12O\n*space_knowledge_domain_file_extension_type\x18\x04 \x01(\x0e\x32\x1b.elint.entity.ExtentionType\x12\x42\n\x16space_knowledge_domain\x18\x05 \x01(\x0b\x32\".elint.entity.SpaceKnowledgeDomain\x12?\n space_knowledge_domain_file_tags\x18\x06 \x03(\x0b\x32\x15.elint.entity.FileTag\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0flast_updated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10last_accessed_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp*5\n\rExtentionType\x12\x07\n\x03PNG\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03PDF\x10\x02\x12\x08\n\x04TEXT\x10\x03\x42/\n\x0c\x65lint.entityB\x1dSpaceKnowledgeDomainFileProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.space_knowledge_domain_file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\035SpaceKnowledgeDomainFileProtoP\001'
  _EXTENTIONTYPE._serialized_start=700
  _EXTENTIONTYPE._serialized_end=753
  _FILETAG._serialized_start=123
  _FILETAG._serialized_end=176
  _SPACEKNOWLEDGEDOMAINFILE._serialized_start=179
  _SPACEKNOWLEDGEDOMAINFILE._serialized_end=698
# @@protoc_insertion_point(module_scope)
