# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/universe.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ethos/elint/entities/universe.proto\x12\x0c\x65lint.entity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x01\n\x08Universe\x12\x13\n\x0buniverse_id\x18\x01 \x01(\t\x12/\n\x0b\x62ig_bang_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\runiverse_name\x18\x03 \x01(\t\x12\x1c\n\x14universe_description\x18\x04 \x01(\t\x12S\n\x1euniverse_recognized_as_country\x18\x05 \x01(\x0b\x32).elint.entity.UniverseRecognizedAsCountryH\x00\x42\x18\n\x16universe_recognized_as\";\n\x1bUniverseRecognizedAsCountry\x12\x1c\n\x14\x63ountry_dialing_code\x18\x01 \x01(\tB\x1f\n\x0c\x65lint.entityB\rUniverseProtoP\x01P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.entities.universe_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014elint.entityB\rUniverseProtoP\001'
  _UNIVERSE._serialized_start=87
  _UNIVERSE._serialized_end=331
  _UNIVERSERECOGNIZEDASCOUNTRY._serialized_start=333
  _UNIVERSERECOGNIZEDASCOUNTRY._serialized_end=392
# @@protoc_insertion_point(module_scope)
