# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gramx/seventy/zero/ethos/gramxpro/multiverse/core/entity/epe_1002/contract.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

from google.protobuf.empty_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPgramx/seventy/zero/ethos/gramxpro/multiverse/core/entity/epe_1002/contract.proto\x12\x41gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1002\x1a\x1bgoogle/protobuf/empty.proto\"0\n\x07\x45PE1002\x12%\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\x16.google.protobuf.EmptyP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1002.contract_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EPE1002._serialized_start=180
  _EPE1002._serialized_end=228
# @@protoc_insertion_point(module_scope)
