# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/service/space_service/access_space_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_service_pb2 as ethos_dot_elint_dot_entities_dot_space__service__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__service__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.space import access_space_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMethos/elint/services/product/service/space_service/access_space_service.proto\x12$elint.services.product.service.space\x1a\"ethos/elint/entities/generic.proto\x1a\"ethos/elint/entities/account.proto\x1a(ethos/elint/entities/space_service.proto\x1a>ethos/elint/services/product/identity/space/access_space.proto\"\xfe\x01\n SpaceServicesAccessTokenResponse\x12\x7f\n*space_service_services_access_auth_details\x18\x01 \x01(\x0b\x32K.elint.services.product.service.space.SpaceServiceServicesAccessAuthDetails\x12*\n\"space_service_services_access_done\x18\x02 \x01(\x08\x12-\n%space_service_services_access_message\x18\x03 \x01(\t\"\x97\x01\n$ValidateSpaceServiceServicesResponse\x12\x35\n-space_service_services_access_validation_done\x18\x01 \x01(\x08\x12\x38\n0space_service_services_access_validation_message\x18\x02 \x01(\t\"\xf6\x01\n%SpaceServiceServicesAccessAuthDetails\x12\x31\n\rspace_service\x18\x01 \x01(\x0b\x32\x1a.elint.entity.SpaceService\x12h\n3space_service_services_access_session_token_details\x18\x02 \x01(\x0b\x32+.elint.entity.PersistentSessionTokenDetails\x12\x30\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x84\x03\n\x19\x41\x63\x63\x65ssSpaceServiceService\x12\xaa\x01\n\x17SpaceServiceAccessToken\x12\x45.elint.services.product.identity.space.SpaceServicesAccessAuthDetails\x1a\x46.elint.services.product.service.space.SpaceServicesAccessTokenResponse\"\x00\x12\xb9\x01\n\x1cValidateSpaceServiceServices\x12K.elint.services.product.service.space.SpaceServiceServicesAccessAuthDetails\x1aJ.elint.services.product.service.space.ValidateSpaceServiceServicesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.service.space_service.access_space_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPACESERVICESACCESSTOKENRESPONSE']._serialized_start=298
  _globals['_SPACESERVICESACCESSTOKENRESPONSE']._serialized_end=552
  _globals['_VALIDATESPACESERVICESERVICESRESPONSE']._serialized_start=555
  _globals['_VALIDATESPACESERVICESERVICESRESPONSE']._serialized_end=706
  _globals['_SPACESERVICESERVICESACCESSAUTHDETAILS']._serialized_start=709
  _globals['_SPACESERVICESERVICESACCESSAUTHDETAILS']._serialized_end=955
  _globals['_ACCESSSPACESERVICESERVICE']._serialized_start=958
  _globals['_ACCESSSPACESERVICESERVICE']._serialized_end=1346
# @@protoc_insertion_point(module_scope)
