# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.space import access_space_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2
from ethos.elint.services.product.service.space_service import access_space_service_pb2 as ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2


class AccessSpaceServiceServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpaceServiceAccessToken = channel.unary_unary(
                '/elint.services.product.service.space.AccessSpaceServiceService/SpaceServiceAccessToken',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2.SpaceServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServicesAccessTokenResponse.FromString,
                )
        self.ValidateSpaceServiceServices = channel.unary_unary(
                '/elint.services.product.service.space.AccessSpaceServiceService/ValidateSpaceServiceServices',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServiceServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.ValidateSpaceServiceServicesResponse.FromString,
                )


class AccessSpaceServiceServiceServicer(object):
    """Service Definitions
    """

    def SpaceServiceAccessToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSpaceServiceServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessSpaceServiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpaceServiceAccessToken': grpc.unary_unary_rpc_method_handler(
                    servicer.SpaceServiceAccessToken,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2.SpaceServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServicesAccessTokenResponse.SerializeToString,
            ),
            'ValidateSpaceServiceServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSpaceServiceServices,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServiceServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.ValidateSpaceServiceServicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.service.space.AccessSpaceServiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessSpaceServiceService(object):
    """Service Definitions
    """

    @staticmethod
    def SpaceServiceAccessToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.space.AccessSpaceServiceService/SpaceServiceAccessToken',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_space_dot_access__space__pb2.SpaceServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServicesAccessTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateSpaceServiceServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.space.AccessSpaceServiceService/ValidateSpaceServiceServices',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServiceServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.ValidateSpaceServiceServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
