# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.service.space_service import create_space_service_pb2 as ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2


class CreateSpaceServiceServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccountSpaceService = channel.unary_unary(
                '/elint.services.product.service.space.CreateSpaceServiceService/CreateAccountSpaceService',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2.CreateAccountSpaceServiceRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2.CreateAccountSpaceServiceResponse.FromString,
                )


class CreateSpaceServiceServiceServicer(object):
    """Service Definitions
    """

    def CreateAccountSpaceService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateSpaceServiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccountSpaceService': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccountSpaceService,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2.CreateAccountSpaceServiceRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2.CreateAccountSpaceServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.service.space.CreateSpaceServiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreateSpaceServiceService(object):
    """Service Definitions
    """

    @staticmethod
    def CreateAccountSpaceService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.space.CreateSpaceServiceService/CreateAccountSpaceService',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2.CreateAccountSpaceServiceRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_create__space__service__pb2.CreateAccountSpaceServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
