# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.service.space_service import access_space_service_pb2 as ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2
from ethos.elint.services.product.service.space_service import discover_space_service_pb2 as ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2


class DiscoverSpaceServiceServiceStub(object):
    """Service Definitions

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSpaceServiceDomains = channel.unary_unary(
                '/elint.services.product.service.space.DiscoverSpaceServiceService/GetSpaceServiceDomains',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServiceServicesAccessAuthDetails.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainsResponse.FromString,
                )
        self.GetSpaceServiceDomainById = channel.unary_unary(
                '/elint.services.product.service.space.DiscoverSpaceServiceService/GetSpaceServiceDomainById',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainByIdRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainByIdResponse.FromString,
                )
        self.GetDomainsByCollarCode = channel.unary_unary(
                '/elint.services.product.service.space.DiscoverSpaceServiceService/GetDomainsByCollarCode',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetDomainsByCollarCodeRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetDomainsByCollarCodeResponse.FromString,
                )


class DiscoverSpaceServiceServiceServicer(object):
    """Service Definitions

    """

    def GetSpaceServiceDomains(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpaceServiceDomainById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDomainsByCollarCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoverSpaceServiceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSpaceServiceDomains': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpaceServiceDomains,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServiceServicesAccessAuthDetails.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainsResponse.SerializeToString,
            ),
            'GetSpaceServiceDomainById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpaceServiceDomainById,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainByIdRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainByIdResponse.SerializeToString,
            ),
            'GetDomainsByCollarCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDomainsByCollarCode,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetDomainsByCollarCodeRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetDomainsByCollarCodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.service.space.DiscoverSpaceServiceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscoverSpaceServiceService(object):
    """Service Definitions

    """

    @staticmethod
    def GetSpaceServiceDomains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.space.DiscoverSpaceServiceService/GetSpaceServiceDomains',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_access__space__service__pb2.SpaceServiceServicesAccessAuthDetails.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSpaceServiceDomainById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.space.DiscoverSpaceServiceService/GetSpaceServiceDomainById',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainByIdRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetSpaceServiceDomainByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDomainsByCollarCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.service.space.DiscoverSpaceServiceService/GetDomainsByCollarCode',
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetDomainsByCollarCodeRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_service_dot_space__service_dot_discover__space__service__pb2.GetDomainsByCollarCodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
