# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge_domain_file_page/create_space_knowledge_domain_file_page.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_knowledge_domain_file_page_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__page__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__page__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__page__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.knowledge.space_knowledge_domain_file import access_space_knowledge_domain_file_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_access__space__knowledge__domain__file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nuethos/elint/services/product/knowledge/space_knowledge_domain_file_page/create_space_knowledge_domain_file_page.proto\x12%elint.services.product.knowledge.page\x1a\"ethos/elint/entities/generic.proto\x1a;ethos/elint/entities/space_knowledge_domain_file_page.proto\x1akethos/elint/services/product/knowledge/space_knowledge_domain_file/access_space_knowledge_domain_file.proto\"\x81\x01\n\x1c\x45xtractPagesFromFileResponse\x12\x19\n\x11total_pages_count\x18\x01 \x01(\x05\x12\x1d\n\x15\x65xtracted_pages_count\x18\x02 \x01(\x05\x12\x11\n\tmeta_done\x18\x03 \x01(\x08\x12\x14\n\x0cmeta_message\x18\x04 \x01(\t\"F\n\x1b\x45xtractTextFromPageResponse\x12\x11\n\tmeta_done\x18\x01 \x01(\x08\x12\x14\n\x0cmeta_message\x18\x02 \x01(\t2\xf1\x02\n)CreateSpaceKnowledgeDomainFilePageService\x12\xb9\x01\n\x14\x45xtractPagesFromFile\x12X.elint.services.product.knowledge.file.SpaceKnowledgeDomainFileServicesAccessAuthDetails\x1a\x43.elint.services.product.knowledge.page.ExtractPagesFromFileResponse\"\x00\x30\x01\x12\x87\x01\n\x13\x45xtractTextFromPage\x12*.elint.entity.SpaceKnowledgeDomainFilePage\x1a\x42.elint.services.product.knowledge.page.ExtractTextFromPageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.knowledge.space_knowledge_domain_file_page.create_space_knowledge_domain_file_page_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXTRACTPAGESFROMFILERESPONSE']._serialized_start=367
  _globals['_EXTRACTPAGESFROMFILERESPONSE']._serialized_end=496
  _globals['_EXTRACTTEXTFROMPAGERESPONSE']._serialized_start=498
  _globals['_EXTRACTTEXTFROMPAGERESPONSE']._serialized_end=568
  _globals['_CREATESPACEKNOWLEDGEDOMAINFILEPAGESERVICE']._serialized_start=571
  _globals['_CREATESPACEKNOWLEDGEDOMAINFILEPAGESERVICE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
