# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from community.apps.gramx.fifty.zero.epn.epn_peers import entities_pb2 as community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2


class EAMV7101DiscoverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EAMC7101 = channel.stream_unary(
                '/community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7101DiscoverService/EAMC7101',
                request_serializer=community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2.EAMV7100.SerializeToString,
                response_deserializer=community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2.EAMV7101.FromString,
                )


class EAMV7101DiscoverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EAMC7101(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EAMV7101DiscoverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EAMC7101': grpc.stream_unary_rpc_method_handler(
                    servicer.EAMC7101,
                    request_deserializer=community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2.EAMV7100.FromString,
                    response_serializer=community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2.EAMV7101.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7101DiscoverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EAMV7101DiscoverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EAMC7101(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7101DiscoverService/EAMC7101',
            community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2.EAMV7100.SerializeToString,
            community_dot_apps_dot_gramx_dot_fifty_dot_zero_dot_epn_dot_epn__peers_dot_entities__pb2.EAMV7101.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
