# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: community/apps/gramx/fifty/zero/epn/epn_peers/entities.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<community/apps/gramx/fifty/zero/epn/epn_peers/entities.proto\x12-community.apps.gramx.fifty.zero.epn.epn_peers\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\x08\x45\x41MV7100\x12\x11\n\teamvt7100\x18\x01 \x01(\t\"i\n\x08\x45\x41MV7101\x12\x11\n\teamvt7101\x18\x01 \x01(\t\x12\x11\n\teamvt7102\x18\x02 \x01(\t\x12\x11\n\teamvt7103\x18\x03 \x03(\t\x12\x11\n\teamvt7104\x18\x04 \x01(\t\x12\x11\n\teamvt7105\x18\x05 \x01(\x08\"V\n\x08\x45\x41MV7103\x12J\n\teamvt7111\x18\x01 \x03(\x0b\x32\x37.community.apps.gramx.fifty.zero.epn.epn_peers.EAMV7102\"\x85\x01\n\x08\x45\x41MV7102\x12\x11\n\teamvt7106\x18\x01 \x01(\t\x12\x11\n\teamvt7107\x18\x02 \x01(\t\x12\x11\n\teamvt7108\x18\x03 \x03(\t\x12\x11\n\teamvt7109\x18\x04 \x03(\t\x12-\n\teamvt7110\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1d\n\x08\x45\x41MV7104\x12\x11\n\teamvt7112\x18\x01 \x01(\t\"C\n\x08\x45\x41MV7105\x12\x11\n\teamvt7113\x18\x01 \x01(\t\x12\x11\n\teamvt7114\x18\x02 \x01(\t\x12\x11\n\teamvt7115\x18\x03 \x01(\x08\"\x1d\n\x08\x45\x41MV7106\x12\x11\n\teamvt7116\x18\x01 \x01(\t\"i\n\x08\x45\x41MV7107\x12\x11\n\teamvt7117\x18\x01 \x01(\t\x12\x11\n\teamvt7118\x18\x02 \x01(\t\x12\x11\n\teamvt7119\x18\x03 \x01(\t\x12\x11\n\teamvt7120\x18\x04 \x01(\t\x12\x11\n\teamvt7121\x18\x05 \x01(\tBgZegithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities;entitiesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'community.apps.gramx.fifty.zero.epn.epn_peers.entities_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zegithub.com/50gramx/eapp-golang-domain/community/apps/gramx/fifty/zero/epn/epn_peers/entities;entities'
  _globals['_EAMV7100']._serialized_start=144
  _globals['_EAMV7100']._serialized_end=173
  _globals['_EAMV7101']._serialized_start=175
  _globals['_EAMV7101']._serialized_end=280
  _globals['_EAMV7103']._serialized_start=282
  _globals['_EAMV7103']._serialized_end=368
  _globals['_EAMV7102']._serialized_start=371
  _globals['_EAMV7102']._serialized_end=504
  _globals['_EAMV7104']._serialized_start=506
  _globals['_EAMV7104']._serialized_end=535
  _globals['_EAMV7105']._serialized_start=537
  _globals['_EAMV7105']._serialized_end=604
  _globals['_EAMV7106']._serialized_start=606
  _globals['_EAMV7106']._serialized_end=635
  _globals['_EAMV7107']._serialized_start=637
  _globals['_EAMV7107']._serialized_end=742
# @@protoc_insertion_point(module_scope)
