# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge_domain_file_page_para/create_space_knowledge_domain_file_page_para.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.knowledge.space_knowledge_domain_file_page import access_space_knowledge_domain_file_page_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file__page_dot_access__space__knowledge__domain__file__page__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x7f\x65thos/elint/services/product/knowledge/space_knowledge_domain_file_page_para/create_space_knowledge_domain_file_page_para.proto\x12%elint.services.product.knowledge.para\x1a\"ethos/elint/entities/generic.proto\x1auethos/elint/services/product/knowledge/space_knowledge_domain_file_page/access_space_knowledge_domain_file_page.proto2\xc4\x01\n-CreateSpaceKnowledgeDomainFilePageParaService\x12\x92\x01\n\x14\x45xtractParasFromPage\x12\\.elint.services.product.knowledge.page.SpaceKnowledgeDomainFilePageServicesAccessAuthDetails\x1a\x1a.elint.entity.ResponseMeta\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.knowledge.space_knowledge_domain_file_page_para.create_space_knowledge_domain_file_page_para_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATESPACEKNOWLEDGEDOMAINFILEPAGEPARASERVICE']._serialized_start=326
  _globals['_CREATESPACEKNOWLEDGEDOMAINFILEPAGEPARASERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
