# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gramx/fifty/zero/ethos/identity/multiverse/core/entity/epme_1005/capability/discover_epme_1005.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gramx.fifty.zero.ethos.identity.multiverse.core.entity.epme_1005 import contract_pb2 as gramx_dot_fifty_dot_zero_dot_ethos_dot_identity_dot_multiverse_dot_core_dot_entity_dot_epme__1005_dot_contract__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = gramx_dot_fifty_dot_zero_dot_ethos_dot_identity_dot_multiverse_dot_core_dot_entity_dot_epme__1005_dot_contract__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = gramx_dot_fifty_dot_zero_dot_ethos_dot_identity_dot_multiverse_dot_core_dot_entity_dot_epme__1005_dot_contract__pb2.google.protobuf.timestamp_pb2
from gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1001 import contract_pb2 as gramx_dot_seventy_dot_zero_dot_ethos_dot_gramxpro_dot_multiverse_dot_core_dot_entity_dot_epe__1001_dot_contract__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\ndgramx/fifty/zero/ethos/identity/multiverse/core/entity/epme_1005/capability/discover_epme_1005.proto\x12\\gramx.fifty.zero.ethos.identity.multiverse.core.entity.epme_1005.capability.context.discover\x1aOgramx/fifty/zero/ethos/identity/multiverse/core/entity/epme_1005/contract.proto\x1aPgramx/seventy/zero/ethos/gramxpro/multiverse/core/entity/epe_1001/contract.proto2\xbe\x01\n\x10\x44iscoverEPME1005\x12\xa9\x01\n\tEPMCC2101\x12J.gramx.fifty.zero.ethos.identity.multiverse.core.entity.epme_1005.EPME1005\x1aJ.gramx.seventy.zero.ethos.gramxpro.multiverse.core.entity.epe_1001.EPE1001\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gramx.fifty.zero.ethos.identity.multiverse.core.entity.epme_1005.capability.discover_epme_1005_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISCOVEREPME1005._serialized_start=362
  _DISCOVEREPME1005._serialized_end=552
# @@protoc_insertion_point(module_scope)
