# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/cognitive/assist/knowledge/generator_knowledge.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_knowledge_domain_file_page_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__page__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__page__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__file__page__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nIethos/elint/services/cognitive/assist/knowledge/generator_knowledge.proto\x12\x33\x65lint.services.cognitive.assist.knowledge.generator\x1a;ethos/elint/entities/space_knowledge_domain_file_page.proto\"W\n\x1bGeneratePageQuestionRequest\x12\x38\n\x04page\x18\x01 \x01(\x0b\x32*.elint.entity.SpaceKnowledgeDomainFilePage\"1\n\x1cGeneratePageQuestionResponse\x12\x11\n\tquestions\x18\x01 \x03(\t2\xdb\x01\n\x19GeneratorKnowledgeService\x12\xbd\x01\n\x14GeneratePageQuestion\x12P.elint.services.cognitive.assist.knowledge.generator.GeneratePageQuestionRequest\x1aQ.elint.services.cognitive.assist.knowledge.generator.GeneratePageQuestionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.cognitive.assist.knowledge.generator_knowledge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERATEPAGEQUESTIONREQUEST']._serialized_start=191
  _globals['_GENERATEPAGEQUESTIONREQUEST']._serialized_end=278
  _globals['_GENERATEPAGEQUESTIONRESPONSE']._serialized_start=280
  _globals['_GENERATEPAGEQUESTIONRESPONSE']._serialized_end=329
  _globals['_GENERATORKNOWLEDGESERVICE']._serialized_start=332
  _globals['_GENERATORKNOWLEDGESERVICE']._serialized_end=551
# @@protoc_insertion_point(module_scope)
