# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge_domain/update_space_knowledge_domain.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\naethos/elint/services/product/knowledge/space_knowledge_domain/update_space_knowledge_domain.proto\x12\'elint.services.product.knowledge.domain\"\'\n%UpdateSpaceKnowledgeDomainNameRequest\"(\n&UpdateSpaceKnowledgeDomainNameResponse2\xe9\x01\n!UpdateSpaceKnowledgeDomainService\x12\xc3\x01\n\x1eUpdateSpaceKnowledgeDomainName\x12N.elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameRequest\x1aO.elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ethos.elint.services.product.knowledge.space_knowledge_domain.update_space_knowledge_domain_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPDATESPACEKNOWLEDGEDOMAINNAMEREQUEST']._serialized_start=142
  _globals['_UPDATESPACEKNOWLEDGEDOMAINNAMEREQUEST']._serialized_end=181
  _globals['_UPDATESPACEKNOWLEDGEDOMAINNAMERESPONSE']._serialized_start=183
  _globals['_UPDATESPACEKNOWLEDGEDOMAINNAMERESPONSE']._serialized_end=223
  _globals['_UPDATESPACEKNOWLEDGEDOMAINSERVICE']._serialized_start=226
  _globals['_UPDATESPACEKNOWLEDGEDOMAINSERVICE']._serialized_end=459
# @@protoc_insertion_point(module_scope)
