# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gramx/fifty/zero/ethos/identity/multiverse/core/entity/epme_1005/contract.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nOgramx/fifty/zero/ethos/identity/multiverse/core/entity/epme_1005/contract.proto\x12@gramx.fifty.zero.ethos.identity.multiverse.core.entity.epme_1005\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n\x08\x45PME1005\x12\x1c\n\x14\x61\x63\x63ount_assistant_id\x18\x01 \x01(\t\x12\x1e\n\x16\x61\x63\x63ount_assistant_name\x18\x02 \x01(\t\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12.\n\ncreated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10last_assisted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampP\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gramx.fifty.zero.ethos.identity.multiverse.core.entity.epme_1005.contract_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EPME1005._serialized_start=183
  _EPME1005._serialized_end=377
# @@protoc_insertion_point(module_scope)
